version: "3.3"

services:
  app:
    build: .
    command: bash start.sh
    restart: on-failure
   variables:
      - name: WARP_ID
        value: $WARP_ID
      - name: SEND_LOG
        value: $SEND_LOG
      - name: BOT_TOKEN
        value: $BOT_TOKEN
      - name: CHANNEL_ID
        value: $CHANNEL_ID
      - name: HIDE_ID
        value: $HIDE_ID
        
